### PR TITLE
Fix/ruby 20 compatibility

### PR DESCRIPTION
**Pull request by kke**
Replace `arr.map{|a| [a, b]}.to_h` with `Hash[*arr.flat_map{|a| [a,b]}]` because Ruby 2.0 does not have Array#to_h

### CODE REVIEW

**Comment by kke** [comment]
The rubocop error has been fixed in [rubocop master](https://github.com/bbatsov/rubocop/issues/3358) (august) but not in the latest version on rubygems (july).

**Comment by kke** [comment]
Could you hit retry for the tests, i think they should pass now as there's a new version of rubocop that has fixed the method missing class scope thing.

ping @betawaffle

**Comment by betawaffle** [comment]
@kke Looks like they still failed

**Comment by kke** [comment]
I have now disabled the failing rubocop test. 

Anyway, the error is not related  to this PR, it occurs with master too.

**Comment by betawaffle** [comment]
Cool stuff. Thanks @kke

**Pull request merged**
